### ISSUE TITLE
Terraform apply error - Error running command 

### ISSUE THREAD

**Issue by Fabian190595** [LaurentLesle/azure_terraform_blueprint_aks_engine#1]
**What might be causing this issue**

![image](https://user-images.githubusercontent.com/34114680/57380530-b92cac80-71db-11e9-805e-eda1bb2cbc4f.png)

**Comment by LaurentLesle** [comment]
Hi @Fabian190595 in which OS / environment did you run the terraform? At the moment it has to be on a MacOS or Linux or Windows Linux subsystem to work.
There is also a limitation in this initial version and you must create the _run folder as per the README.md where you execute the terraform

**Comment by Fabian190595** [comment]
Hi @LaurentLesle, I am running it on Windows OS and I did create _run folder. 

![image](https://user-images.githubusercontent.com/34114680/57388166-3fe88600-71ea-11e9-9482-c555f33dee91.png).

I tried running it on the azure portal integrated powershell but it threw a similar error.

![image](https://user-images.githubusercontent.com/34114680/57389126-1d576c80-71ec-11e9-8431-6bf9c18da833.png)

Below are the steps that I did prior to terraform apply and may I ask if kubeconfig has to be set before terraform apply?

1. terraform init
1. terraform plan
1. terraform apply

**Comment by LaurentLesle** [comment]
Can you try running either:

- azure portal integrated BASH shell
- Windows Linux Subsystem - Ubuntu on Windows

I tested on both. Let me know

Note: after the terraform apply complete successfully you will have to set the kubeconfig variable

**Comment by Fabian190595** [comment]
Hi @LaurentLesle , thanks for the tips. I was able to run it on the WSL flawlessly.

![image](https://user-images.githubusercontent.com/34114680/57458870-b5189180-72a4-11e9-9515-608c232b4927.png)
